apiVersion: v1
kind: Service
metadata:
  name: docker-registry
  namespace: docker-registry
spec:
  type: ClusterIP
  selector:
    app: registry
  ports:
  - port: 5001
    protocol: TCP
    targetPort: 5000
