apiVersion: v1
kind: PersistentVolume
metadata:
  name: certs-registry
  namespace: docker-registry
spec:
  capacity:
    storage: 2G
  accessModes:
  - ReadWriteOnce
  local:
    path: /node-registry-certs
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - {key: kubernetes.io/hostname, operator: In, values: [ip-172-26-1-141]}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: certs-registry
  namespace: docker-registry
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 2G
  storageClassName: ""
