apiVersion: v1
kind: Service
metadata:
  name: grafana
  namespace: ft-services
  annotations:
    metallb.universe.tf/allow-shared-ip: ft-services
spec:
  type: LoadBalancer
  selector:
    app: grafana
  ports:
  - name: grafana
    protocol: TCP
    port: 3000
    targetPort: 3000
    nodePort: 3000
