apiVersion: v1
kind: Service
metadata:
 name: phpmyadmin
 namespace: ft-services
 annotations:
  metallb.universe.tf/allow-shared-ip: ft-services
 labels:
  app: phpmyadmin
spec:
 type: LoadBalancer
 selector:
  app: phpmyadmin
 ports:
  - name: phpmyadmin
    protocol: TCP
    port: 5000
    targetPort: 5000
    nodePort: 5000
