apiVersion: v1
kind: Service
metadata:
  name: nginx
  namespace: ft-services
  annotations:
    metallb.universe.tf/allow-shared-ip: ft-services
spec:
  type: LoadBalancer
  selector:
    app: nginx
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 80
    nodePort: 80
  - name: https
    protocol: TCP
    port: 443
    targetPort: 443
    nodePort: 443
  - name: ssh
    protocol: TCP
    port: 22
    targetPort: 22
    nodePort: 22
