apiVersion: v1
kind: Service
metadata:
 name: wordpress
 namespace: ft-services
 annotations:
  metallb.universe.tf/allow-shared-ip: ft-services
 labels:
  app: wordpress
spec:
 type: LoadBalancer
 selector:
  app: wordpress
 ports:
 - port: 5050
   name: wordpress
   targetPort: 5050
   nodePort: 5050
