apiVersion: v1
kind: Service
metadata:
 name: mysql
 namespace: ft-services
 labels:
  app: mysql
spec:
 type: ClusterIP
 selector:
  app: mysql
  tier: mysql
 ports:
 - port: 3306
   targetPort: 3306
