apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-ftps
  namespace: ft-services
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 5G
  storageClassName: ""
