apiVersion: v1
kind: Service
metadata:
 name: ftps
 namespace: ft-services
 annotations:
  metallb.universe.tf/allow-shared-ip: ft-services
 labels:
  app: ftps
spec:
 type: LoadBalancer
 selector:
  app: ftps
 ports:
 - name: ftps
   protocol: TCP
   port: 21
   targetPort: 21
   nodePort: 21
 - name: ftps2
   protocol: TCP
   port: 20
   targetPort: 20
   nodePort: 20
 - name: ftps3
   protocol: TCP
   port: 30020
   targetPort: 30020
   nodePort: 30020
 - name: ftps4
   protocol: TCP
   port: 30021
   targetPort: 30021
   nodePort: 30021
