apiVersion: v1
kind: PersistentVolume
metadata:
 name: pv-influxdb
 namespace: ft-services
spec:
 capacity:
  storage: 2G
 accessModes:
  - ReadWriteOnce
 local:
  path: /node-influxdb
 nodeAffinity:
  required:
   nodeSelectorTerms:
   - matchExpressions:
     - {key: kubernetes.io/hostname, operator: In, values: [ip-172-26-1-141]}
